sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8'
before_script:
- npm prune
script:
- npm run ci
- npm run build
- npm install codecov -g
after_success:
- codecov
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"